<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerCs2v4be\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerCs2v4be/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerCs2v4be\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerCs2v4be\appDevDebugProjectContainer();
